// components/BlogPage.tsx
export function BlogPage() {
  return (
    <main className="min-h-screen bg-white text-black">
      <header className="bg-gray-50 border-b border-gray-200 p-6">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <h1 className="text-2xl font-bold">TrendWise</h1>
          <nav className="space-x-6">
            <a href="#" className="text-gray-600 hover:text-black">Home</a>
            <a href="#" className="text-gray-600 hover:text-black">Blog</a>
            <a href="#" className="text-gray-600 hover:text-black">About</a>
            <a href="#" className="text-gray-600 hover:text-black">Contact</a>
          </nav>
        </div>
      </header>

      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4">
          <h2 className="text-4xl font-bold mb-4">Latest Articles</h2>
          <p className="text-gray-500 mb-12 max-w-2xl">
            Explore fresh, AI-generated content based on current trending topics. Stay informed with our curated articles.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {[1, 2, 3, 4, 5, 6].map((i) => (
              <article key={i} className="bg-gray-50 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition duration-300">
                <div className="h-48 bg-gray-200" />
                <div className="p-6">
                  <span className="text-sm text-blue-600 font-medium">Technology</span>
                  <h3 className="text-xl font-semibold mt-2 mb-3">Generated Blog Title #{i}</h3>
                  <p className="text-gray-600 text-sm line-clamp-3">
                    This is a sample preview of the blog content generated by AI. It gives users a short snippet of what to expect.
                  </p>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <footer className="bg-gray-50 border-t border-gray-200 p-6 mt-16">
        <div className="max-w-7xl mx-auto text-center text-gray-500">
          © 2025 TrendWise. All rights reserved.
        </div>
      </footer>
    </main>
  );
}
